### ISSUE TITLE
Add `x-enum-varnames` and `x-enum-descriptions` to enums

### ISSUE THREAD

**Issue by dragonfleas** [s-crypt/IGDB-OpenAPI#5]
# Description

Right now the enums that are generated using any of the OpenAPI Typescript code gen are very bad, the description only exists within a TS/JSDoc and the var names themselves are just `NUMBER_N = N` instead of `VARNAME = N`

## Proposed Solution

- Add `x-enum-varnames` and `x-enum-descriptions` to enums as described here: https://openapi-ts.pages.dev/advanced#enum-extensions

This ensures typescript generation has proper var naming, and intellisense hover description.

https://github.com/s-crypt/IGDB-OpenAPI/blob/c3b6f28bdd5e28fdac3f1f8d6b0f7a5617ae0254/IGDB-OpenAPI.yaml#L1998-L2010

Would go to

```
    AgeRatingCategoryEnums:
      type: integer
      format: int32
      enum: [1, 2, 3, 4, 5, 6, 7]
      x-enum-varnames:
        - ESRB
        - PEGI
        - CERO
        - USK
        - GRAC
        - CLASS_IND
        - ACB
      x-enum-descriptions:
        - 'ESRB'
        - 'PEGI'
        - 'CERO'
        - 'USK'
        - 'GRAC'
        - 'CLASS_IND'
        - 'ACB'
      description: |
        The organization that has issued a specific rating  
        1: ESRB  
        2: PEGI  
        3: CERO  
        4: USK  
        5: GRAC  
        6: CLASS_IND  
        7: ACB
```

I'd like to contribute these changes if you'd assign the issue to me.
